with distinct_side_orders as (

select 

distinct
to_date(DATE, 'YYYY-MM-DD') as DATE,
TO_TIME(RIGHT(TRIM(TIME), 8)) AS TIME,
CAST(ORDER_DETAILS_ID AS NUMBER) as ORDER_DETAILS_ID,
CAST(ORDER_ID AS NUMBER) as ORDER_ID,
upper(PIZZA_ID) as PIZZA_ID,
upper(PIZZA_TYPE_ID) as PIZZA_TYPE_ID,
upper(SIZE) as SIZE,
upper(CATEGORY) as CATEGORY,
CAST(QUANTITY AS NUMBER) AS QUANTITY,
CAST(PRICE AS FLOAT) AS PRICE,
DESSERTS,
CAST(DESSERTS_QUANTITY AS NUMBER) AS DESSERTS_QUANTITY,
CAST(DESSERTPRICE AS FLOAT) AS DESSERTPRICE,

SIDE_ORDER,
CAST(SIDE_ORDERS_QUANTITY AS NUMBER) as SIDE_ORDERS_QUANTITY,
CAST(SIDE_ORDER_PRICE AS FLOAT) as SIDE_ORDER_PRICE,
DRINKS,
CAST(DRINKS_QUANTITY AS NUMBER) as DRINKS_QUANTITY,
CAST(DRINKS_PRICE AS FLOAT) as DRINKS_PRICE

 from 
{{ source('dominos_pizza', 'side_orders') }}

)




select 
ORDER_DETAILS_ID,
ORDER_ID,
initcap(DESSERTS) as DESSERTS,
DESSERTS_QUANTITY,
DESSERTPRICE
from distinct_side_orders