WITH source_data AS (
    SELECT 

        DISTINCT
        TO_DATE(DATE, 'YYYY-MM-DD') AS DATE,
        -- Ensure proper time formatting and parse to the time type
        TO_TIME(RIGHT(TRIM(TIME), 8), 'HH24:MI:SS') AS TIME,

        CAST(ORDER_DETAILS_ID AS NUMBER) AS ORDER_DETAILS_ID,
        CAST(ORDER_ID AS NUMBER) AS ORDER_ID,

        UPPER(PIZZA_ID) AS PIZZA_ID,
        UPPER(PIZZA_TYPE_ID) AS PIZZA_TYPE_ID,
        UPPER(SIZE) AS SIZE,
        UPPER(CATEGORY) AS CATEGORY,
        CAST(QUANTITY AS NUMBER) AS QUANTITY,
        CAST(PRICE AS FLOAT) AS PRICE,

        DESSERTS,
        CAST(DESSERTS_QUANTITY AS NUMBER) AS DESSERTS_QUANTITY,
        CAST(DESSERTPRICE AS FLOAT) AS DESSERTPRICE,

        SIDE_ORDER,
        CAST(SIDE_ORDERS_QUANTITY AS NUMBER) AS SIDE_ORDERS_QUANTITY,
        CAST(SIDE_ORDER_PRICE AS FLOAT) AS SIDE_ORDER_PRICE,

        DRINKS,
        CAST(DRINKS_QUANTITY AS NUMBER) AS DRINKS_QUANTITY,
        CAST(DRINKS_PRICE AS FLOAT) AS DRINKS_PRICE
    FROM 
        {{ source('dominos_pizza', 'side_orders') }}
)



select * from source_data